# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
      - master
      - dev
      - hotfix/*
      - release/*
      - feature/*
  pull_request:
    branches:
      - master
  workflow_dispatch:   # <-- вот это даёт ручной запуск

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Cross.CQRS.EF.sln'

    runs-on: ubuntu-22.04 # ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: 5.12.0

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          useConfigFile: true

      - name: Show env variables
        run: env

      - name: Restore dependencies
        run: dotnet restore

#      - name: Build
#        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore -p:Version=${{ env.semVer }}

      - name: Build
        run: |
          dotnet build "$SOLUTION" --configuration "$BUILD_CONFIG" --no-restore \
            -p:Configuration=$BUILD_CONFIG \
            -p:Version=${GitVersion_SemVer} \
            -p:AssemblyVersion=${GitVersion_AssemblySemVer} \
            -p:FileVersion=${GitVersion_AssemblySemFileVer} \
            -p:InformationalVersion="${GitVersion_InformationalVersion}" \
            -p:Company="Denis Peshkov" \
            -p:Product="Cross.CQRS.EF" \
            -p:Description="Simple .NET MediatR base EF Transactional Behavior and Paginated Queries and Paginated Models. Published on Nuget at https://www.nuget.org/packages/Cross.CQRS.EF" \
            -p:RepositoryUrl="https://github.com/denis-peshkov/Cross.CQRS.EF.git" \
            -p:RepositoryType=git \
            -p:CLSCompliant=true \
            -p:NeutralLanguage=en

      - name: Run tests
        run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v5 # Ex: v4.0.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
        with:
#          projectBaseDir: app/
#          args: >
#            -Dsonar.organization=peshkov
#            -Dsonar.projectKey=Cross.CQRS.EF
#            -Dsonar.python.coverage.reportPaths=coverage.xml
#            -Dsonar.sources=Cross.CQRS.EF/
#            -Dsonar.tests=tests/
#            -Dsonar.test.exclusions=tests/**
#            -Dsonar.verbose=true
          args: >
            -Dsonar.organization=peshkov
            -Dsonar.projectKey=Cross.CQRS.EF
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=Cross.CQRS.EF/
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Nuget Pack
        run: nuget pack _nuget/config.nuspec -Symbols -Version ${{ env.semVer }}

      - name: ref
        run: echo "github.head_ref 1 ${{ github.head_ref }} 2 $GITHUB_REF 3 ${{ github.ref }}"

      - name: Create git Tag
        if: ${{ contains('refs/heads/hotfix', github.ref) || contains('refs/heads/hotfix', github.ref) || contains('refs/heads/master', github.ref) }}
        run: |
          git tag v${{ env.semVer }}

      - name: Push git Tag
        if: ${{ contains(fromJson('["refs/heads/master", "refs/heads/release", "refs/heads/hotfix"]'), github.ref) }}
        run: |
          git config --global user.name 'Denis Peshkov'
          git config --global user.email 'denis.peshkov@outlook.com'
          git remote set-url origin https://x-access-token:${{ secrets.TAGTOKEN }}@github.com/${{ github.repository }}
          git push origin v${{ env.semVer }}

      - name: Nuget Push
        if: ${{ !startsWith(github.ref, 'refs/pull') }}
        run: nuget push **/Cross.CQRS.EF.${{ env.semVer }}.symbols.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source "https://api.nuget.org/v3/index.json" -SkipDuplicate
